<?php
return [
    'ThanhVien' => [
        'table' => 'ThanhVien',
        'pk' => ['MaThanhVien'],
        'title' => 'Thành viên',
        'select' => 'ThanhVien.*, VaiTro.TenVaiTro',
        'join' => 'LEFT JOIN VaiTro ON VaiTro.MaVaiTro = ThanhVien.MaVaiTro',
        'order' => 'ThanhVien.MaThanhVien ASC',
        'fields' => [
            'MaThanhVien' => ['label' => 'Mã số', 'type' => 'text', 'required' => true, 'max_length' => 50],
            'HoTen' => ['label' => 'Họ tên', 'type' => 'text', 'required' => true, 'max_length' => 100],
            'Email' => ['label' => 'Email', 'type' => 'email', 'required' => true, 'max_length' => 100],
            'MatKhau' => ['label' => 'Mật khẩu', 'type' => 'text', 'required' => true, 'max_length' => 255],
            'MaVaiTro' => ['label' => 'Vai trò', 'type' => 'select', 'relation' => ['table' => 'VaiTro', 'value' => 'MaVaiTro', 'label' => 'TenVaiTro'], 'required' => true],
            'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
        ],
        'list' => ['MaThanhVien' => 'Mã số', 'HoTen' => 'Họ tên', 'Email' => 'Email', 'MatKhau' => 'Mật khẩu', 'TenVaiTro' => 'Vai trò', 'NgayTao' => 'Ngày tạo'],
    ],
    'LoaiSuKien' => [
        'table' => 'LoaiSuKien',
        'pk' => ['MaLoaiSuKien'],
        'title' => 'Loại sự kiện',
        'order' => 'LoaiSuKien.MaLoaiSuKien ASC',
        'fields' => [
            'MaLoaiSuKien' => ['label' => 'Mã loại', 'type' => 'text', 'required' => true, 'max_length' => 50],
            'TenLoaiSuKien' => ['label' => 'Tên loại sự kiện', 'type' => 'text', 'required' => true, 'max_length' => 100],
            'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
        ],
        'list' => ['MaLoaiSuKien' => 'Mã loại', 'TenLoaiSuKien' => 'Tên loại', 'MoTa' => 'Mô tả'],
    ],
    'SuKien' => [
        'table' => 'SuKien',
        'pk' => ['MaSuKien'],
        'title' => 'Sự kiện',
        'select' => 'SuKien.*, ThanhVien.HoTen AS NguoiToChucTen, LoaiSuKien.TenLoaiSuKien',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = SuKien.NguoiToChuc LEFT JOIN LoaiSuKien ON LoaiSuKien.MaLoaiSuKien = SuKien.MaLoaiSuKien',
        'order' => 'SuKien.NgayBatDau DESC, SuKien.MaSuKien ASC',
        'fields' => [
            'MaSuKien' => ['label' => 'Mã sự kiện', 'type' => 'text', 'required' => true, 'max_length' => 50],
            'TenSuKien' => ['label' => 'Tên sự kiện', 'type' => 'text', 'required' => true, 'max_length' => 100],
            'MaLoaiSuKien' => ['label' => 'Loại sự kiện', 'type' => 'select', 'relation' => ['table' => 'LoaiSuKien', 'value' => 'MaLoaiSuKien', 'label' => 'TenLoaiSuKien'], 'required' => true],
            'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
            'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
            'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
            'NgayBatDau' => ['label' => 'Ngày bắt đầu', 'type' => 'datetime', 'required' => true],
            'NgayKetThuc' => ['label' => 'Ngày kết thúc', 'type' => 'datetime', 'required' => true],
            'NguoiToChuc' => ['label' => 'Người tổ chức', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
        ],
        'list' => ['MaSuKien' => 'Mã sự kiện', 'TenSuKien' => 'Tên sự kiện', 'TenLoaiSuKien' => 'Loại', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'NguoiToChucTen' => 'Người tổ chức', 'NgayBatDau' => 'Bắt đầu', 'NgayKetThuc' => 'Kết thúc'],
    ],
    'NhomHocTap' => [
        'table' => 'NhomHocTap',
        'pk' => ['MaNhom'],
        'title' => 'Nhóm học tập',
        'select' => 'NhomHocTap.*, ThanhVien.HoTen AS TroGiangTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = NhomHocTap.TroGiang',
        'order' => 'NhomHocTap.MaNhom ASC',
        'fields' => [
            'MaNhom' => ['label' => 'Mã nhóm', 'type' => 'text', 'required' => true, 'max_length' => 50],
            'TenNhom' => ['label' => 'Tên nhóm', 'type' => 'text', 'required' => true, 'max_length' => 100],
            'TroGiang' => ['label' => 'Trợ giảng', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
            'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
        ],
        'list' => ['MaNhom' => 'Mã nhóm', 'TenNhom' => 'Tên nhóm', 'TroGiangTen' => 'Trợ giảng', 'NgayTao' => 'Ngày tạo', 'MoTa' => 'Mô tả'],
    ],
    'DiemDanh' => [
        'table' => 'DiemDanh',
        'pk' => ['MaDiemDanh'],
        'auto' => ['MaDiemDanh'],
        'title' => 'Điểm danh',
        'select' => 'DiemDanh.*, NhomHocTap.TenNhom, ThanhVien.HoTen',
        'join' => 'LEFT JOIN NhomHocTap ON NhomHocTap.MaNhom = DiemDanh.MaNhom LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = DiemDanh.MaThanhVien',
        'order' => 'DiemDanh.NgayDiemDanh DESC, DiemDanh.MaDiemDanh DESC',
        'fields' => [
            'MaDiemDanh' => ['label' => 'Mã điểm danh', 'type' => 'number', 'readonly' => true],
            'MaNhom' => ['label' => 'Nhóm', 'type' => 'select', 'relation' => ['table' => 'NhomHocTap', 'value' => 'MaNhom', 'label' => 'TenNhom'], 'required' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayDiemDanh' => ['label' => 'Ngày điểm danh', 'type' => 'date', 'required' => true],
            'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select_static', 'options' => ['Có mặt' => 'Có mặt', 'Vắng' => 'Vắng', 'Muộn' => 'Muộn'], 'required' => true],
            'GhiChu' => ['label' => 'Ghi chú', 'type' => 'textarea'],
        ],
        'list' => ['MaDiemDanh' => 'Mã', 'TenNhom' => 'Nhóm', 'HoTen' => 'Thành viên', 'NgayDiemDanh' => 'Ngày', 'TrangThai' => 'Trạng thái', 'GhiChu' => 'Ghi chú'],
    ],
    'BaiDang' => [
        'table' => 'BaiDang',
        'pk' => ['MaBaiDang'],
        'title' => 'Bài đăng',
        'select' => 'BaiDang.*, ThanhVien.HoTen AS TacGiaTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = BaiDang.TacGia',
        'order' => 'BaiDang.NgayTao DESC, BaiDang.MaBaiDang ASC',
        'fields' => [
            'MaBaiDang' => ['label' => 'Mã bài đăng', 'type' => 'text', 'required' => true, 'max_length' => 50],
            'TieuDe' => ['label' => 'Tiêu đề', 'type' => 'text', 'required' => true, 'max_length' => 255],
            'Anh' => ['label' => 'Ảnh', 'type' => 'image', 'required' => true],
            'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
            'TacGia' => ['label' => 'Tác giả', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
        ],
        'list' => ['MaBaiDang' => 'Mã', 'TieuDe' => 'Tiêu đề', 'Anh' => 'Ảnh', 'NoiDung' => 'Nội dung', 'TacGiaTen' => 'Tác giả', 'NgayTao' => 'Ngày tạo'],
    ],
    'ThanhVienSuKien' => [
        'table' => 'ThanhVienSuKien',
        'pk' => ['MaSuKien', 'MaThanhVien'],
        'title' => 'Thành viên tham gia sự kiện',
        'select' => 'ThanhVienSuKien.*, SuKien.TenSuKien, ThanhVien.HoTen, NguoiXacNhan.HoTen AS XacNhanBoiTen',
        'join' => 'LEFT JOIN SuKien ON SuKien.MaSuKien = ThanhVienSuKien.MaSuKien LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = ThanhVienSuKien.MaThanhVien LEFT JOIN ThanhVien NguoiXacNhan ON NguoiXacNhan.MaThanhVien = ThanhVienSuKien.XacNhanBoi',
        'order' => 'ThanhVienSuKien.NgayDangKy DESC',
        'ajaxConfirm' => true,
        'fields' => [
            'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayDangKy' => ['label' => 'Ngày đăng ký', 'type' => 'datetime'],
            'TrangThaiThamGia' => ['label' => 'Trạng thái tham gia', 'type' => 'select_static', 'options' => ['Đã đăng ký' => 'Đã đăng ký', 'Đã tham gia' => 'Đã tham gia', 'Vắng' => 'Vắng'], 'required' => true],
            'NgayXacNhan' => ['label' => 'Ngày xác nhận', 'type' => 'datetime', 'nullable' => true],
            'XacNhanBoi' => ['label' => 'Xác nhận bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'nullable' => true],
        ],
        'list' => ['TenSuKien' => 'Sự kiện', 'HoTen' => 'Thành viên', 'NgayDangKy' => 'Ngày đăng ký', 'TrangThaiThamGia' => 'Trạng thái', 'NgayXacNhan' => 'Ngày xác nhận', 'XacNhanBoiTen' => 'Xác nhận bởi'],
    ],
    'QuyTacDiemRenLuyen' => [
        'table' => 'QuyTacDiemRenLuyen',
        'pk' => ['MaQuyTac'],
        'auto' => ['MaQuyTac'],
        'title' => 'Quy tắc điểm rèn luyện',
        'select' => 'QuyTacDiemRenLuyen.*, LoaiSuKien.TenLoaiSuKien',
        'join' => 'LEFT JOIN LoaiSuKien ON LoaiSuKien.MaLoaiSuKien = QuyTacDiemRenLuyen.MaLoaiSuKien',
        'order' => 'QuyTacDiemRenLuyen.NamHoc DESC, QuyTacDiemRenLuyen.HocKy ASC',
        'fields' => [
            'MaQuyTac' => ['label' => 'Mã quy tắc', 'type' => 'number', 'readonly' => true],
            'MaLoaiSuKien' => ['label' => 'Loại sự kiện', 'type' => 'select', 'relation' => ['table' => 'LoaiSuKien', 'value' => 'MaLoaiSuKien', 'label' => 'TenLoaiSuKien'], 'required' => true],
            'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
            'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
            'Diem' => ['label' => 'Điểm', 'type' => 'number', 'required' => true, 'min' => 0],
            'GhiChu' => ['label' => 'Ghi chú', 'type' => 'textarea'],
        ],
        'list' => ['MaQuyTac' => 'Mã', 'TenLoaiSuKien' => 'Loại sự kiện', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'Diem' => 'Điểm', 'GhiChu' => 'Ghi chú'],
    ],
    'DiemRenLuyen' => [
        'table' => 'DiemRenLuyen',
        'pk' => ['MaDiem'],
        'auto' => ['MaDiem'],
        'title' => 'Điểm rèn luyện',
        'select' => 'DiemRenLuyen.*, ThanhVien.HoTen, SuKien.TenSuKien, QuyTacDiemRenLuyen.Diem AS DiemQuyTac',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = DiemRenLuyen.MaThanhVien LEFT JOIN SuKien ON SuKien.MaSuKien = DiemRenLuyen.MaSuKien LEFT JOIN QuyTacDiemRenLuyen ON QuyTacDiemRenLuyen.MaQuyTac = DiemRenLuyen.MaQuyTac',
        'order' => 'DiemRenLuyen.NgayCong DESC, DiemRenLuyen.MaDiem DESC',
        'fields' => [
            'MaDiem' => ['label' => 'Mã điểm', 'type' => 'number', 'readonly' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
            'MaQuyTac' => ['label' => 'Quy tắc điểm', 'type' => 'select', 'relation' => ['table' => 'QuyTacDiemRenLuyen', 'value' => 'MaQuyTac', 'label' => 'MaQuyTac'], 'required' => true],
            'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
            'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
            'SoDiem' => ['label' => 'Số điểm', 'type' => 'number', 'required' => true, 'min' => 0],
            'NgayCong' => ['label' => 'Ngày cộng', 'type' => 'datetime'],
            'GhiChu' => ['label' => 'Ghi chú', 'type' => 'textarea'],
        ],
        'list' => ['MaDiem' => 'Mã', 'HoTen' => 'Thành viên', 'TenSuKien' => 'Sự kiện', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'SoDiem' => 'Điểm', 'NgayCong' => 'Ngày cộng', 'GhiChu' => 'Ghi chú'],
    ],
    'TongDiemRenLuyen' => [
        'table' => 'TongDiemRenLuyen',
        'pk' => ['MaTongDiem'],
        'auto' => ['MaTongDiem'],
        'title' => 'Tổng điểm rèn luyện',
        'select' => 'TongDiemRenLuyen.*, ThanhVien.HoTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = TongDiemRenLuyen.MaThanhVien',
        'order' => 'TongDiemRenLuyen.NamHoc DESC, TongDiemRenLuyen.HocKy ASC, ThanhVien.MaThanhVien ASC',
        'fields' => [
            'MaTongDiem' => ['label' => 'Mã tổng điểm', 'type' => 'number', 'readonly' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
            'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
            'TongDiem' => ['label' => 'Tổng điểm', 'type' => 'number', 'required' => true, 'min' => 0],
            'CapNhatLuc' => ['label' => 'Cập nhật lúc', 'type' => 'datetime'],
        ],
        'list' => ['MaTongDiem' => 'Mã', 'HoTen' => 'Thành viên', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'TongDiem' => 'Tổng điểm', 'CapNhatLuc' => 'Cập nhật lúc'],
    ],
    'ChungNhan' => [
        'table' => 'ChungNhan',
        'pk' => ['MaChungNhan'],
        'title' => 'Chứng nhận',
        'select' => 'ChungNhan.*, SuKien.TenSuKien, ThanhVien.HoTen, NguoiCap.HoTen AS CapBoiTen',
        'join' => 'LEFT JOIN SuKien ON SuKien.MaSuKien = ChungNhan.MaSuKien LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = ChungNhan.MaThanhVien LEFT JOIN ThanhVien NguoiCap ON NguoiCap.MaThanhVien = ChungNhan.CapBoi',
        'order' => 'ChungNhan.NgayCap DESC',
        'fields' => [
            'MaChungNhan' => ['label' => 'Mã chứng nhận', 'type' => 'text', 'required' => true, 'max_length' => 100],
            'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayCap' => ['label' => 'Ngày cấp', 'type' => 'datetime'],
            'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
            'CapBoi' => ['label' => 'Cấp bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'nullable' => true],
        ],
        'list' => ['MaChungNhan' => 'Mã chứng nhận', 'TenSuKien' => 'Sự kiện', 'HoTen' => 'Thành viên', 'NgayCap' => 'Ngày cấp', 'NoiDung' => 'Nội dung', 'CapBoiTen' => 'Cấp bởi'],
    ],
    'BaoCao' => [
        'table' => 'BaoCao',
        'pk' => ['MaBaoCao'],
        'auto' => ['MaBaoCao'],
        'title' => 'Báo cáo',
        'select' => 'BaoCao.*, ThanhVien.HoTen AS NopBoiTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = BaoCao.NopBoi',
        'order' => 'BaoCao.NgayNop DESC',
        'fields' => [
            'MaBaoCao' => ['label' => 'Mã báo cáo', 'type' => 'number', 'readonly' => true],
            'TieuDe' => ['label' => 'Tiêu đề', 'type' => 'text', 'required' => true, 'max_length' => 100],
            'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
            'NopBoi' => ['label' => 'Nộp bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayNop' => ['label' => 'Ngày nộp', 'type' => 'datetime'],
        ],
        'list' => ['MaBaoCao' => 'Mã', 'TieuDe' => 'Tiêu đề', 'NoiDung' => 'Nội dung', 'NopBoiTen' => 'Nộp bởi', 'NgayNop' => 'Ngày nộp'],
    ],
];
