<?php
return [
    'ThanhVien' => [
        'table' => 'ThanhVien',
        'pk' => ['MaThanhVien'],
        'title' => 'Thành viên',
        'select' => 'ThanhVien.*, VaiTro.TenVaiTro',
        'join' => 'LEFT JOIN VaiTro ON VaiTro.MaVaiTro = ThanhVien.MaVaiTro',
        'order' => 'ThanhVien.MaThanhVien ASC',
        'fields' => [
            'MaThanhVien' => ['label' => 'Mã số', 'type' => 'text', 'required' => true],
            'HoTen' => ['label' => 'Họ tên', 'type' => 'text', 'required' => true],
            'Email' => ['label' => 'Email', 'type' => 'email', 'required' => true],
            'MatKhau' => ['label' => 'Mật khẩu', 'type' => 'text', 'required' => true],
            'MaVaiTro' => ['label' => 'Vai trò', 'type' => 'select', 'relation' => ['table' => 'VaiTro', 'value' => 'MaVaiTro', 'label' => 'TenVaiTro'], 'required' => true],
            'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
        ],
        'list' => ['MaThanhVien' => 'Mã số', 'HoTen' => 'Họ tên', 'Email' => 'Email', 'MatKhau' => 'Mật khẩu', 'TenVaiTro' => 'Vai trò', 'NgayTao' => 'Ngày tạo'],
    ],
    'SuKien' => [
        'table' => 'SuKien',
        'pk' => ['MaSuKien'],
        'title' => 'Sự kiện',
        'select' => 'SuKien.*, ThanhVien.HoTen AS NguoiToChucTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = SuKien.NguoiToChuc',
        'order' => 'SuKien.NgayBatDau DESC, SuKien.MaSuKien ASC',
        'fields' => [
            'MaSuKien' => ['label' => 'Mã sự kiện', 'type' => 'text', 'required' => true],
            'TenSuKien' => ['label' => 'Tên sự kiện', 'type' => 'text', 'required' => true],
            'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
            'NgayBatDau' => ['label' => 'Ngày bắt đầu', 'type' => 'datetime', 'required' => true],
            'NgayKetThuc' => ['label' => 'Ngày kết thúc', 'type' => 'datetime', 'required' => true],
            'NguoiToChuc' => ['label' => 'Người tổ chức', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
        ],
        'list' => ['MaSuKien' => 'Mã sự kiện', 'TenSuKien' => 'Tên sự kiện', 'MoTa' => 'Mô tả', 'NguoiToChucTen' => 'Người tổ chức', 'NgayBatDau' => 'Bắt đầu', 'NgayKetThuc' => 'Kết thúc'],
    ],
    'NhomHocTap' => [
        'table' => 'NhomHocTap',
        'pk' => ['MaNhom'],
        'title' => 'Nhóm học tập',
        'select' => 'NhomHocTap.*, ThanhVien.HoTen AS TroGiangTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = NhomHocTap.TroGiang',
        'order' => 'NhomHocTap.MaNhom ASC',
        'fields' => [
            'MaNhom' => ['label' => 'Mã nhóm', 'type' => 'text', 'required' => true],
            'TenNhom' => ['label' => 'Tên nhóm', 'type' => 'text', 'required' => true],
            'TroGiang' => ['label' => 'Trợ giảng', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
            'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
        ],
        'list' => ['MaNhom' => 'Mã nhóm', 'TenNhom' => 'Tên nhóm', 'TroGiangTen' => 'Trợ giảng', 'NgayTao' => 'Ngày tạo', 'MoTa' => 'Mô tả'],
    ],
    'DiemDanh' => [
        'table' => 'DiemDanh',
        'pk' => ['MaDiemDanh'],
        'auto' => ['MaDiemDanh'],
        'title' => 'Điểm danh',
        'select' => 'DiemDanh.*, NhomHocTap.TenNhom, ThanhVien.HoTen',
        'join' => 'LEFT JOIN NhomHocTap ON NhomHocTap.MaNhom = DiemDanh.MaNhom LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = DiemDanh.MaThanhVien',
        'order' => 'DiemDanh.NgayDiemDanh DESC, DiemDanh.MaDiemDanh DESC',
        'fields' => [
            'MaDiemDanh' => ['label' => 'Mã điểm danh', 'type' => 'number', 'readonly' => true],
            'MaNhom' => ['label' => 'Nhóm', 'type' => 'select', 'relation' => ['table' => 'NhomHocTap', 'value' => 'MaNhom', 'label' => 'TenNhom'], 'required' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayDiemDanh' => ['label' => 'Ngày điểm danh', 'type' => 'date', 'required' => true],
            'TrangThai' => ['label' => 'Trạng thái', 'type' => 'select_static', 'options' => ['Có mặt' => 'Có mặt', 'Vắng' => 'Vắng', 'Muộn' => 'Muộn'], 'required' => true],
            'GhiChu' => ['label' => 'Ghi chú', 'type' => 'textarea'],
        ],
        'list' => ['MaDiemDanh' => 'Mã', 'TenNhom' => 'Nhóm', 'HoTen' => 'Thành viên', 'NgayDiemDanh' => 'Ngày', 'TrangThai' => 'Trạng thái', 'GhiChu' => 'Ghi chú'],
    ],
    'BaiDang' => [
        'table' => 'BaiDang',
        'pk' => ['MaBaiDang'],
        'title' => 'Bài đăng',
        'select' => 'BaiDang.*, ThanhVien.HoTen AS TacGiaTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = BaiDang.TacGia',
        'order' => 'BaiDang.NgayTao DESC, BaiDang.MaBaiDang ASC',
        'fields' => [
            'MaBaiDang' => ['label' => 'Mã bài đăng', 'type' => 'text', 'required' => true],
            'TieuDe' => ['label' => 'Tiêu đề', 'type' => 'text', 'required' => true],
            'Anh' => ['label' => 'Ảnh', 'type' => 'image', 'required' => true],
            'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
            'TacGia' => ['label' => 'Tác giả', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
        ],
        'list' => ['MaBaiDang' => 'Mã', 'TieuDe' => 'Tiêu đề', 'Anh' => 'Ảnh', 'NoiDung' => 'Nội dung', 'TacGiaTen' => 'Tác giả', 'NgayTao' => 'Ngày tạo'],
    ],
    'ThanhVienSuKien' => [
        'table' => 'ThanhVienSuKien',
        'pk' => ['MaSuKien', 'MaThanhVien'],
        'title' => 'Thành viên tham gia sự kiện',
        'select' => 'ThanhVienSuKien.*, SuKien.TenSuKien, ThanhVien.HoTen',
        'join' => 'LEFT JOIN SuKien ON SuKien.MaSuKien = ThanhVienSuKien.MaSuKien LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = ThanhVienSuKien.MaThanhVien',
        'order' => 'ThanhVienSuKien.NgayDangKy DESC',
        'fields' => [
            'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
            'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayDangKy' => ['label' => 'Ngày đăng ký', 'type' => 'datetime'],
        ],
        'list' => ['TenSuKien' => 'Sự kiện', 'HoTen' => 'Thành viên', 'NgayDangKy' => 'Ngày đăng ký'],
    ],
    'BaoCao' => [
        'table' => 'BaoCao',
        'pk' => ['MaBaoCao'],
        'auto' => ['MaBaoCao'],
        'title' => 'Báo cáo',
        'select' => 'BaoCao.*, ThanhVien.HoTen AS NopBoiTen',
        'join' => 'LEFT JOIN ThanhVien ON ThanhVien.MaThanhVien = BaoCao.NopBoi',
        'order' => 'BaoCao.NgayNop DESC',
        'fields' => [
            'MaBaoCao' => ['label' => 'Mã báo cáo', 'type' => 'number', 'readonly' => true],
            'TieuDe' => ['label' => 'Tiêu đề', 'type' => 'text', 'required' => true],
            'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
            'NopBoi' => ['label' => 'Nộp bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
            'NgayNop' => ['label' => 'Ngày nộp', 'type' => 'datetime'],
        ],
        'list' => ['MaBaoCao' => 'Mã', 'TieuDe' => 'Tiêu đề', 'NoiDung' => 'Nội dung', 'NopBoiTen' => 'Nộp bởi', 'NgayNop' => 'Ngày nộp'],
    ],
];
